# Generated by Django 5.0.6 on 2024-05-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='equiment',
            old_name='description',
            new_name='stud_name',
        ),
    ]
