# Generated by Django 5.0.6 on 2024-05-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiment',
            name='amount',
            field=models.TextField(),
        ),
    ]
