# Generated by Django 5.0.6 on 2024-05-31 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_equiment_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equiment',
            old_name='amount',
            new_name='regno',
        ),
    ]
