# Generated by Django 5.0.6 on 2024-05-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_amount_equiment_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiment',
            name='Lab',
            field=models.CharField(default='Default Lab', max_length=100),
        ),
        migrations.AddField(
            model_name='equiment',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
