# Generated by Django 5.0.6 on 2024-05-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_equiment_lab_equiment_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equiment',
            new_name='Manage_Equiment',
        ),
    ]
