# Generated by Django 5.0.6 on 2024-05-31 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_equiment_manage_equiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eq_name', models.CharField(max_length=100)),
                ('Lab', models.CharField(default='Default Lab', max_length=100)),
                ('eq_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='manage_equiment',
            name='Lab',
        ),
    ]
