# Generated by Django 5.0.6 on 2024-06-01 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_equiment_remove_manage_equiment_lab'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_equiment',
            name='rfidno',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equiment',
            name='Lab',
            field=models.CharField(default='01', max_length=100),
        ),
    ]
