# Generated by Django 5.0.6 on 2024-06-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_manage_equiment_rfidno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_equiment',
            name='rfidno',
        ),
    ]
