# Generated by Django 5.0.6 on 2024-06-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_manage_equiment_rfidno'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_equiment',
            name='rfidno',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
