# Generated by Django 5.0.6 on 2024-06-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_manage_equiment_rfidno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='rfidno',
            field=models.CharField(default='null', max_length=100, unique=True),
        ),
    ]
