# Generated by Django 5.0.6 on 2024-06-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='regno',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='manage_equiment',
            name='stud_name',
            field=models.CharField(max_length=100),
        ),
    ]
