# Generated by Django 5.0.6 on 2024-06-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_manage_equiment_regno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='rfidno',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
