# Generated by Django 5.0.6 on 2024-06-03 12:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_manage_equiment_rfidno'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_equiment',
            name='borrowed_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
