# Generated by Django 5.0.6 on 2024-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_manage_equiment_borrowed_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='borrowed_time',
            field=models.TimeField(),
        ),
    ]
