# Generated by Django 5.0.6 on 2024-06-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_manage_equiment_borrowed_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manage_equiment',
            name='rfidno',
        ),
    ]
