# Generated by Django 5.0.6 on 2024-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_manage_equiment_rfidno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='regno',
            field=models.CharField(max_length=100),
        ),
    ]
