# Generated by Django 5.0.6 on 2024-06-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_manage_equiment_regno'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_equiment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
