# Generated by Django 5.0.6 on 2024-06-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_manage_equiment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_equiment',
            name='returned_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
