# Generated by Django 5.0.6 on 2024-06-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_manage_equiment_returned_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiment',
            name='Lab',
        ),
        migrations.RemoveField(
            model_name='equiment',
            name='eq_name',
        ),
    ]
