# Generated by Django 5.0.6 on 2024-06-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_equiment_lab_remove_equiment_eq_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiment',
            name='eq_id',
        ),
        migrations.AddField(
            model_name='equiment',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equiment',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equiment',
            name='idno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equiment',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
