# Generated by Django 5.0.6 on 2024-06-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_manage_equiment_stud_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
