# Generated by Django 5.0.6 on 2024-06-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_equiment_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='stud_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
