# Generated by Django 5.0.6 on 2024-06-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_rename_date_manage_equiment_borrowed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manage_equiment',
            name='borrowed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
