# Generated by Django 5.0.6 on 2024-06-06 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_manage_equiment_borrowed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='manage_equiment',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manage_equiment',
            name='borrowed_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
