# Generated by Django 5.0.6 on 2024-06-12 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_equiment_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiment',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
