# Generated by Django 5.0.6 on 2024-06-12 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equiment',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
