# Generated by Django 5.0.6 on 2024-06-14 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_student_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiment',
            name='available',
        ),
        migrations.RemoveField(
            model_name='equiment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='equiment',
            name='idno',
        ),
    ]
