# Generated by Django 5.0.6 on 2024-06-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_equiment_available_remove_equiment_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiment',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
