# Generated by Django 5.0.6 on 2024-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-borrowed_at']},
        ),
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='Student_Images'),
        ),
    ]
