# Generated by Django 5.0.6 on 2024-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0002_alter_transaction_options_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='Student_Images'),
        ),
    ]
