# Generated by Django 5.0.6 on 2024-06-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0003_alter_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='Student_Images'),
        ),
    ]
