# Generated by Django 5.0.6 on 2024-06-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0004_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='available_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
