# Generated by Django 5.0.6 on 2024-06-14 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0006_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='borrowed_at',
            field=models.DateTimeField(),
        ),
    ]
