# Generated by Django 5.0.6 on 2024-06-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0007_alter_transaction_borrowed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='available',
        ),
    ]
