# Generated by Django 5.0.6 on 2024-06-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0008_remove_equipment_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='idno',
        ),
    ]
