# Generated by Django 5.0.6 on 2024-06-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0009_remove_equipment_idno'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={},
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='equipment',
        ),
        migrations.AddField(
            model_name='transaction',
            name='equipment',
            field=models.ManyToManyField(to='UApp.equipment'),
        ),
    ]
