# Generated by Django 5.0.6 on 2024-06-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0010_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='orderno',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
