# Generated by Django 5.0.6 on 2024-06-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0011_equipment_orderno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='orderno',
            new_name='order',
        ),
    ]
