# Generated by Django 5.0.6 on 2024-09-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0013_remove_student_course_remove_student_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
