# Generated by Django 5.0.6 on 2024-10-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0014_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='equipmentName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='labName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='studentName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='studentRegno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
