# Generated by Django 5.0.6 on 2024-10-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0017_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='treatment',
            field=models.ManyToManyField(to='UApp.treatment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='treatmentName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
