# Generated by Django 5.0.6 on 2024-11-19 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0019_equipment_unique_equipment_per_lab'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='unique_equipment_per_lab',
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(condition=models.Q(('name__isnull', False)), fields=('lab', 'name'), name='unique_lab_equipment_name', violation_error_message='Equipment name must be unique for each lab (case-insensitive).'),
        ),
    ]
