# Generated by Django 5.0.6 on 2024-11-19 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0020_remove_equipment_unique_equipment_per_lab_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='treatment',
            constraint=models.UniqueConstraint(condition=models.Q(('treatment__isnull', False)), fields=('lab', 'treatment'), name='unique_lab_treatment', violation_error_message='Treatment must be unique for each lab (case-insensitive).'),
        ),
    ]
