# Generated by Django 5.0.6 on 2024-11-19 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0021_treatment_unique_lab_treatment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='medicalkit',
            constraint=models.UniqueConstraint(condition=models.Q(('kitName__isnull', False)), fields=('lab', 'kitName'), name='unique_lab_medical_kit_name', violation_error_message='Medical kit name must be unique for each lab (case-insensitive).'),
        ),
    ]
