# Generated by Django 5.0.6 on 2024-11-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UApp', '0022_medicalkit_unique_lab_medical_kit_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicalkit',
            name='unique_lab_medical_kit_name',
        ),
    ]
